### ISSUE TITLE
Specify the exact string that needs to be printed

### ISSUE THREAD

**Issue by jasny** [Aspirar/hello-world#89]
Different implementations output different strings;

* `hello world`
* `Hello world`
* `Hello World`
* `Hello world!`
* `Hello World!`
* etc

Also, some have line endings, while others don't.

Please specify the exact string that should be outputted.

**Comment by Aspirar** [comment]
It could be any of the above. In fact, some programs here print hello world vertically instead of horizontally, and some print it graphically. It's all about learning something new and having fun in the process :)
